{% set name = "uhttp" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/uhttp-{{ version }}.tar.gz
  sha256: 55baf245be446ba604cae4b9f75a9884c6678d9ab22eb1749eb983ddbfc6bc6d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9,<4.0

test:
  imports:
    - uhttp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/0x67757300/uHTTP
  doc_url: https://0x67757300.github.io/uHTTP/uhttp.html
  summary: ASGI micro framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
